"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Use an env-provided secret key in all non-demo environments.
# Fallback keeps local development working, but does NOT fix production hardening.
SECRET_KEY = str(__import__('os').environ.get('DJANGO_SECRET_KEY', 'django-insecure-local-dev-change-me'))

# SECURITY WARNING: don't run with debug turned on in production!
# Default to False for production-safety; set DJANGO_DEBUG=true for local debugging.
DEBUG = __import__('os').environ.get('DJANGO_DEBUG', 'false').lower() == 'true'


# In production, set ALLOWED_HOSTS to your domain(s) or load from env.
ALLOWED_HOSTS = [h for h in __import__('os').environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,dar-system-backend.onrender.com').split(',') if h.strip()]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'documents',
    'accounts',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # ← Must be FIRST
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
] if (BASE_DIR / 'static').exists() else []

# CORS Settings
import os

CORS_ALLOW_ALL_ORIGINS = False

# Production and development allowed origins
CORS_ALLOWED_ORIGINS = [
    # Local development
    'http://127.0.0.1:5173',
    'http://127.0.0.1:8000',
    'http://localhost:5173',
    'http://localhost:8000',
    # Production
    'https://dar-docs-coral.vercel.app',
]

# Allow additional origins from environment variable if set
if os.environ.get('CORS_ALLOWED_ORIGINS'):
    env_origins = [o.strip() for o in os.environ.get('CORS_ALLOWED_ORIGINS').split(',') if o.strip()]
    CORS_ALLOWED_ORIGINS.extend(env_origins)

# Allow credentials (cookies, authorization headers) in CORS requests
CORS_ALLOW_CREDENTIALS = True

# Allow custom header used by the frontend to identify the acting user in activity logs
CORS_ALLOW_HEADERS = (
    *default_headers,
    'x-user',
)

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'core.exceptions.custom_exception_handler',
}

