import sqlite3
import os
import json
import datetime

def export_sqlite_to_postgres():
    db_path = os.path.join(os.path.dirname(__file__), 'backend', 'db.sqlite3')
    out_path = os.path.join(os.path.dirname(__file__), 'supabase_migration.sql')
    
    if not os.path.exists(db_path):
        print(f"Database not found at {db_path}")
        return

    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()

    # Get all tables
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
    tables = [row['name'] for row in cursor.fetchall() if not row['name'].startswith('sqlite_')]

    with open(out_path, 'w', encoding='utf-8') as f:
        f.write("-- Migration Script from SQLite to PostgreSQL (Supabase)\n\n")

        # Create tables
        for table in tables:
            # We skip some internal Django tables that might not be needed in a pure frontend rewrite,
            # but since we want a 1:1 migration for now, we'll dump all of them just in case.
            cursor.execute(f"PRAGMA table_info({table})")
            columns = cursor.fetchall()
            
            f.write(f'CREATE TABLE IF NOT EXISTS public."{table}" (\n')
            col_defs = []
            for col in columns:
                col_name = col['name']
                col_type = col['type'].upper()
                
                # Basic mapping from SQLite to Postgres
                pg_type = 'TEXT'
                if 'INT' in col_type:
                    pg_type = 'INTEGER'
                elif 'CHAR' in col_type or 'TEXT' in col_type or 'CLOB' in col_type:
                    pg_type = 'TEXT'
                elif 'REAL' in col_type or 'FLOA' in col_type or 'DOUB' in col_type or 'DECIMAL' in col_type:
                    pg_type = 'NUMERIC'
                elif 'DATE' in col_type or 'TIME' in col_type:
                    pg_type = 'TIMESTAMP WITH TIME ZONE'
                elif 'BOOL' in col_type:
                    pg_type = 'BOOLEAN'
                
                # Check for primary key
                pk = ' PRIMARY KEY' if col['pk'] else ''
                not_null = ' NOT NULL' if col['notnull'] else ''
                
                if col['pk'] and 'INT' in col_type:
                    # Use SERIAL or GENERATED BY DEFAULT AS IDENTITY for PK in Postgres
                    col_defs.append(f'  "{col_name}" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
                else:
                    col_defs.append(f'  "{col_name}" {pg_type}{not_null}')
            
            f.write(',\n'.join(col_defs))
            f.write('\n);\n\n')

        # Insert data
        for table in tables:
            cursor.execute(f"PRAGMA table_info({table})")
            col_info = {col['name']: col['type'].upper() for col in cursor.fetchall()}
            
            cursor.execute(f"SELECT * FROM {table}")
            rows = cursor.fetchall()
            if not rows:
                continue

            f.write(f'-- Data for {table}\n')
            
            columns = [key for key in rows[0].keys()]
            col_names = ', '.join([f'"{c}"' for c in columns])
            
            for row in rows:
                values = []
                for key in columns:
                    val = row[key]
                    if val is None:
                        values.append('NULL')
                    elif 'BOOL' in col_info.get(key, ''):
                        values.append('TRUE' if val in (1, '1', True) else 'FALSE')
                    elif isinstance(val, (int, float)):
                        values.append(str(val))
                    else:
                        # Escape single quotes
                        escaped_val = str(val).replace("'", "''")
                        values.append(f"'{escaped_val}'")
                
                val_str = ', '.join(values)
                f.write(f'INSERT INTO public."{table}" ({col_names}) VALUES ({val_str});\n')
            
            f.write('\n')

    print(f"Successfully generated SQL migration script at: {out_path}")

if __name__ == "__main__":
    export_sqlite_to_postgres()
