-- Migration Script from SQLite to PostgreSQL (Supabase)
CREATE TABLE IF NOT EXISTS public."documents_activitylog" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user" TEXT NOT NULL,
  "action" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS public."documents_signatory" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "designation" TEXT NOT NULL,
  "role" TEXT NOT NULL,
  "is_deleted" BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS public."documents_noadocument" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "doc_date" TIMESTAMP WITH TIME ZONE NOT NULL,
  "name" TEXT NOT NULL,
  "position" TEXT NOT NULL,
  "address" TEXT NOT NULL,
  "activity" TEXT NOT NULL,
  "date_of_conduct" TIMESTAMP WITH TIME ZONE NOT NULL,
  "amount" NUMERIC NOT NULL,
  "date_created" TIMESTAMP WITH TIME ZONE NOT NULL,
  "greeting" TEXT NOT NULL,
  "hope_designation" TEXT NOT NULL,
  "hope_name" TEXT NOT NULL,
  "procurement_mop" TEXT NOT NULL,
  "procurement_what" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public."documents_ntpdocument" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "doc_date" TIMESTAMP WITH TIME ZONE NOT NULL,
  "name" TEXT NOT NULL,
  "position" TEXT NOT NULL,
  "address" TEXT NOT NULL,
  "activity" TEXT NOT NULL,
  "date_of_conduct" TIMESTAMP WITH TIME ZONE NOT NULL,
  "amount" NUMERIC NOT NULL,
  "date_created" TIMESTAMP WITH TIME ZONE NOT NULL,
  "greeting" TEXT NOT NULL,
  "hope_designation_ntp" TEXT NOT NULL,
  "hope_name" TEXT NOT NULL,
  "procurement_mop" TEXT NOT NULL,
  "procurement_what" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public."documents_resodirectacquisition" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reso_date" TIMESTAMP WITH TIME ZONE NOT NULL,
  "company_name" TEXT NOT NULL,
  "items_services" TEXT NOT NULL,
  "purpose" TEXT NOT NULL,
  "date_of_conduct" TEXT NOT NULL,
  "max_amount" NUMERIC NOT NULL,
  "award_amount" NUMERIC NOT NULL,
  "date_created" TIMESTAMP WITH TIME ZONE NOT NULL,
  "approved_by_designation" TEXT NOT NULL,
  "approved_by_name" TEXT NOT NULL,
  "chairperson_designation" TEXT NOT NULL,
  "chairperson_name" TEXT NOT NULL,
  "end_user" TEXT NOT NULL,
  "member1_designation" TEXT NOT NULL,
  "member1_name" TEXT NOT NULL,
  "member2_designation" TEXT NOT NULL,
  "member2_name" TEXT NOT NULL,
  "member3_designation" TEXT NOT NULL,
  "member3_name" TEXT NOT NULL,
  "member4_designation" TEXT NOT NULL,
  "member4_name" TEXT NOT NULL,
  "vice_designation" TEXT NOT NULL,
  "vice_name" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public."documents_resoemergencysplit" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reso_date" TIMESTAMP WITH TIME ZONE NOT NULL,
  "company_name" TEXT NOT NULL,
  "items" TEXT NOT NULL,
  "purpose" TEXT NOT NULL,
  "date_of_conduct" TEXT NOT NULL,
  "max_amount" NUMERIC NOT NULL,
  "award_amount" NUMERIC NOT NULL,
  "date_created" TIMESTAMP WITH TIME ZONE NOT NULL,
  "approved_by_designation" TEXT NOT NULL,
  "approved_by_name" TEXT NOT NULL,
  "chairperson_designation" TEXT NOT NULL,
  "chairperson_name" TEXT NOT NULL,
  "end_user" TEXT NOT NULL,
  "member1_designation" TEXT NOT NULL,
  "member1_name" TEXT NOT NULL,
  "member2_designation" TEXT NOT NULL,
  "member2_name" TEXT NOT NULL,
  "member3_designation" TEXT NOT NULL,
  "member3_name" TEXT NOT NULL,
  "member4_designation" TEXT NOT NULL,
  "member4_name" TEXT NOT NULL,
  "vice_designation" TEXT NOT NULL,
  "vice_name" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public."documents_resolov" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reso_date" TIMESTAMP WITH TIME ZONE NOT NULL,
  "company_name" TEXT NOT NULL,
  "purpose" TEXT NOT NULL,
  "date_of_conduct" TEXT NOT NULL,
  "max_amount" NUMERIC NOT NULL,
  "award_amount" NUMERIC NOT NULL,
  "rating_score" TEXT NOT NULL,
  "date_created" TIMESTAMP WITH TIME ZONE NOT NULL,
  "approved_by_designation" TEXT NOT NULL,
  "approved_by_name" TEXT NOT NULL,
  "chairperson_designation" TEXT NOT NULL,
  "chairperson_name" TEXT NOT NULL,
  "end_user" TEXT NOT NULL,
  "lov_lessor_1" TEXT NOT NULL,
  "lov_lessor_2" TEXT NOT NULL,
  "lov_lessor_3" TEXT NOT NULL,
  "member1_designation" TEXT NOT NULL,
  "member1_name" TEXT NOT NULL,
  "member2_designation" TEXT NOT NULL,
  "member2_name" TEXT NOT NULL,
  "member3_designation" TEXT NOT NULL,
  "member3_name" TEXT NOT NULL,
  "member4_designation" TEXT NOT NULL,
  "member4_name" TEXT NOT NULL,
  "vice_designation" TEXT NOT NULL,
  "vice_name" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public."documents_resosvp" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reso_date" TIMESTAMP WITH TIME ZONE NOT NULL,
  "company_name" TEXT NOT NULL,
  "items" TEXT NOT NULL,
  "purpose" TEXT NOT NULL,
  "award_amount" NUMERIC NOT NULL,
  "date_created" TIMESTAMP WITH TIME ZONE NOT NULL,
  "approved_by_designation" TEXT NOT NULL,
  "approved_by_name" TEXT NOT NULL,
  "chairperson_designation" TEXT NOT NULL,
  "chairperson_name" TEXT NOT NULL,
  "end_user" TEXT NOT NULL,
  "member1_designation" TEXT NOT NULL,
  "member1_name" TEXT NOT NULL,
  "member2_designation" TEXT NOT NULL,
  "member2_name" TEXT NOT NULL,
  "member3_designation" TEXT NOT NULL,
  "member3_name" TEXT NOT NULL,
  "member4_designation" TEXT NOT NULL,
  "member4_name" TEXT NOT NULL,
  "vice_designation" TEXT NOT NULL,
  "vice_name" TEXT NOT NULL
);

-- Canonical tables for the current DAR app in Supabase
CREATE TABLE IF NOT EXISTS public.auth_metadata (
  uid UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  user_level SMALLINT NOT NULL CHECK (user_level IN (1, 2)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO public."documents_signatory" ("id", "name", "designation", "role", "is_deleted") VALUES (3, 'ATTY. ROMIN A. CADIENTE', 'Member', 'Member', FALSE);
INSERT INTO public."documents_signatory" ("id", "name", "designation", "role", "is_deleted") VALUES (4, 'BEN B. RIOS', 'Member', 'Member', FALSE);
INSERT INTO public."documents_signatory" ("id", "name", "designation", "role", "is_deleted") VALUES (5, 'BOBBY S. BAUTISTA', 'Member', 'Member', FALSE);
INSERT INTO public."documents_signatory" ("id", "name", "designation", "role", "is_deleted") VALUES (6, 'BOBBY S. BALTAZAR', 'Member', 'Member', FALSE);
INSERT INTO public."documents_signatory" ("id", "name", "designation", "role", "is_deleted") VALUES (7, 'MARIA ANA B. FRANCISCO, CESO III', 'Regional Director', 'HOPE', FALSE);
INSERT INTO public."documents_signatory" ("id", "name", "designation", "role", "is_deleted") VALUES (8, 'ATTY. GLAIZA MAE MASAOY-ONIA', 'Chairperson', 'Chairperson', FALSE);
INSERT INTO public."documents_signatory" ("id", "name", "designation", "role", "is_deleted") VALUES (9, 'NENITA C. MADRIAGA', 'Vice Chairperson', 'Vice Chairperson', FALSE);

