# Generated by Django 6.0.5 on 2026-05-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NOADocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_date', models.DateField(verbose_name='Document Date')),
                ('name', models.CharField(max_length=255, verbose_name='Name of Representative / Company')),
                ('position', models.CharField(max_length=255, verbose_name='Position')),
                ('address', models.TextField(verbose_name='Address')),
                ('activity', models.CharField(max_length=500, verbose_name='Activity / Project Title')),
                ('date_of_conduct', models.DateField(verbose_name='Date of Conduct')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NTPDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_date', models.DateField(verbose_name='Document Date')),
                ('name', models.CharField(max_length=255, verbose_name='Name of Representative / Company')),
                ('position', models.CharField(max_length=255, verbose_name='Position')),
                ('address', models.TextField(verbose_name='Address')),
                ('activity', models.CharField(max_length=500, verbose_name='Activity / Project Title')),
                ('date_of_conduct', models.DateField(verbose_name='Date of Conduct')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResoDirectAcquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reso_date', models.DateField(verbose_name='Resolution Date')),
                ('company_name', models.CharField(max_length=255, verbose_name='Awardee Company Name')),
                ('items_services', models.CharField(max_length=500, verbose_name='Items / Services')),
                ('purpose', models.CharField(max_length=500, verbose_name='Meeting / Purpose')),
                ('date_of_conduct', models.CharField(max_length=255, verbose_name='Date of Conduct / Period')),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Max ABC Amount')),
                ('award_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Award Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
