# Generated by Django 6.0.5 on 2026-05-18 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noadocument',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='ntpdocument',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='resodirectacquisition',
            old_name='created_at',
            new_name='date_created',
        ),
    ]
