# Generated by Django 6.0.5 on 2026-05-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_rename_created_at_noadocument_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResoEmergencySplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reso_date', models.DateField(verbose_name='Resolution Date')),
                ('company_name', models.CharField(max_length=255, verbose_name='Awardee Company Name')),
                ('items', models.CharField(max_length=500, verbose_name='Specific Goods / Items')),
                ('purpose', models.CharField(max_length=500, verbose_name='Activity Name')),
                ('date_of_conduct', models.CharField(max_length=255, verbose_name='Date of Activity')),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount based on PR')),
                ('award_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Award Amount')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResoLOV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reso_date', models.DateField(verbose_name='Resolution Date')),
                ('company_name', models.CharField(max_length=255, verbose_name='Awardee Company Name')),
                ('purpose', models.CharField(max_length=500, verbose_name='Activity Name')),
                ('date_of_conduct', models.CharField(max_length=255, verbose_name='Date of Activity')),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ABC Amount')),
                ('award_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Award Amount')),
                ('rating_score', models.CharField(max_length=50, verbose_name='Rating Score')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResoSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reso_date', models.DateField(verbose_name='Resolution Date')),
                ('company_name', models.CharField(max_length=255, verbose_name='Awardee Company Name')),
                ('items', models.CharField(max_length=500, verbose_name='Specific Goods / Items')),
                ('purpose', models.CharField(max_length=500, verbose_name='Activity / Purpose')),
                ('award_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Award Amount')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
