# Generated by Django 6.0.5 on 2026-05-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Signatory Name')),
                ('designation', models.CharField(max_length=255, verbose_name='Designation')),
                ('role', models.CharField(max_length=100, verbose_name='Role / Category')),
            ],
        ),
    ]
