# Generated by Django 6.0.5 on 2026-05-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_signatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='signatory',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is Deleted'),
        ),
    ]
