# Generated by Django 6.0.5 on 2026-05-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_signatory_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='noadocument',
            name='greeting',
            field=models.CharField(blank=True, default="Ma'am/Sir", max_length=50, verbose_name='Greeting Salutation'),
        ),
        migrations.AddField(
            model_name='noadocument',
            name='hope_designation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='HOPE Signatory Designation'),
        ),
        migrations.AddField(
            model_name='noadocument',
            name='hope_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='HOPE Signatory Name'),
        ),
        migrations.AddField(
            model_name='noadocument',
            name='procurement_mop',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Mode of Procurement (MOP)'),
        ),
        migrations.AddField(
            model_name='noadocument',
            name='procurement_what',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Procurement Item (WHAT?)'),
        ),
        migrations.AddField(
            model_name='ntpdocument',
            name='greeting',
            field=models.CharField(blank=True, default="Ma'am/Sir", max_length=50, verbose_name='Greeting Salutation'),
        ),
        migrations.AddField(
            model_name='ntpdocument',
            name='hope_designation_ntp',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='HOPE Signatory Designation (NTP)'),
        ),
        migrations.AddField(
            model_name='ntpdocument',
            name='hope_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='HOPE Signatory Name'),
        ),
        migrations.AddField(
            model_name='ntpdocument',
            name='procurement_mop',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Mode of Procurement (MOP)'),
        ),
        migrations.AddField(
            model_name='ntpdocument',
            name='procurement_what',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Procurement Item (WHAT?)'),
        ),
        migrations.AddField(
            model_name='resodirectacquisition',
            name='approved_by_designation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Approved By Designation'),
        ),
        migrations.AddField(
            model_name='resodirectacquisition',
            name='approved_by_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Approved By Name'),
        ),
        migrations.AddField(
            model_name='resodirectacquisition',
            name='chairperson_designation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Chairperson Designation'),
        ),
        migrations.AddField(
            model_name='resodirectacquisition',
            name='chairperson_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Chairperson Name'),
        ),
        migrations.AddField(
            model_name='resodirectacquisition',
            name='end_user',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='End-user/Rep. Name'),
        ),
        migrations.AddField(
            model_name='resodirectacquisition',
            name='member1_designation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Member 1 Designation'),
        ),
        migrations.AddField(
            model_name='resodirectacquisition',
            name='member1_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Member 1 Name'),
        ),
        migrations.AddField(
            model_name='resodirectacquisition',
            name='member2_designation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Member 2 Designation'),
        ),
        migrations.AddField(
            model_name='resodirectacquisition',
            name='member2_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Member 2 Name'),
        ),
        migrations.AddField(
            model_name='resodirectacquisition',
            name='member3_designation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Member 3 Designation'),
        ),
        migrations.AddField(
            model_name='resodirectacquisition',
            name='member3_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Member 3 Name'),
        ),
        migrations.AddField(
            model_name='resodirectacquisition',
            name='member4_designation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Member 4 Designation'),
        ),
        migrations.AddField(
            model_name='resodirectacquisition',
            name='member4_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Member 4 Name'),
        ),
        migrations.AddField(
            model_name='resodirectacquisition',
            name='vice_designation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Vice Chairperson Designation'),
        ),
        migrations.AddField(
            model_name='resodirectacquisition',
            name='vice_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Vice Chairperson Name'),
        ),
        migrations.AddField(
            model_name='resoemergencysplit',
            name='approved_by_designation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Approved By Designation'),
        ),
        migrations.AddField(
            model_name='resoemergencysplit',
            name='approved_by_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Approved By Name'),
        ),
        migrations.AddField(
            model_name='resoemergencysplit',
            name='chairperson_designation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Chairperson Designation'),
        ),
        migrations.AddField(
            model_name='resoemergencysplit',
            name='chairperson_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Chairperson Name'),
        ),
        migrations.AddField(
            model_name='resoemergencysplit',
            name='end_user',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='End-user/Rep. Name'),
        ),
        migrations.AddField(
            model_name='resoemergencysplit',
            name='member1_designation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Member 1 Designation'),
        ),
        migrations.AddField(
            model_name='resoemergencysplit',
            name='member1_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Member 1 Name'),
        ),
        migrations.AddField(
            model_name='resoemergencysplit',
            name='member2_designation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Member 2 Designation'),
        ),
        migrations.AddField(
            model_name='resoemergencysplit',
            name='member2_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Member 2 Name'),
        ),
        migrations.AddField(
            model_name='resoemergencysplit',
            name='member3_designation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Member 3 Designation'),
        ),
        migrations.AddField(
            model_name='resoemergencysplit',
            name='member3_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Member 3 Name'),
        ),
        migrations.AddField(
            model_name='resoemergencysplit',
            name='member4_designation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Member 4 Designation'),
        ),
        migrations.AddField(
            model_name='resoemergencysplit',
            name='member4_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Member 4 Name'),
        ),
        migrations.AddField(
            model_name='resoemergencysplit',
            name='vice_designation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Vice Chairperson Designation'),
        ),
        migrations.AddField(
            model_name='resoemergencysplit',
            name='vice_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Vice Chairperson Name'),
        ),
        migrations.AddField(
            model_name='resolov',
            name='approved_by_designation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Approved By Designation'),
        ),
        migrations.AddField(
            model_name='resolov',
            name='approved_by_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Approved By Name'),
        ),
        migrations.AddField(
            model_name='resolov',
            name='chairperson_designation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Chairperson Designation'),
        ),
        migrations.AddField(
            model_name='resolov',
            name='chairperson_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Chairperson Name'),
        ),
        migrations.AddField(
            model_name='resolov',
            name='end_user',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='End-user/Rep. Name'),
        ),
        migrations.AddField(
            model_name='resolov',
            name='lov_lessor_1',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Lessor/Supplier 1'),
        ),
        migrations.AddField(
            model_name='resolov',
            name='lov_lessor_2',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Lessor/Supplier 2'),
        ),
        migrations.AddField(
            model_name='resolov',
            name='lov_lessor_3',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Lessor/Supplier 3'),
        ),
        migrations.AddField(
            model_name='resolov',
            name='member1_designation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Member 1 Designation'),
        ),
        migrations.AddField(
            model_name='resolov',
            name='member1_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Member 1 Name'),
        ),
        migrations.AddField(
            model_name='resolov',
            name='member2_designation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Member 2 Designation'),
        ),
        migrations.AddField(
            model_name='resolov',
            name='member2_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Member 2 Name'),
        ),
        migrations.AddField(
            model_name='resolov',
            name='member3_designation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Member 3 Designation'),
        ),
        migrations.AddField(
            model_name='resolov',
            name='member3_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Member 3 Name'),
        ),
        migrations.AddField(
            model_name='resolov',
            name='member4_designation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Member 4 Designation'),
        ),
        migrations.AddField(
            model_name='resolov',
            name='member4_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Member 4 Name'),
        ),
        migrations.AddField(
            model_name='resolov',
            name='vice_designation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Vice Chairperson Designation'),
        ),
        migrations.AddField(
            model_name='resolov',
            name='vice_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Vice Chairperson Name'),
        ),
        migrations.AddField(
            model_name='resosvp',
            name='approved_by_designation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Approved By Designation'),
        ),
        migrations.AddField(
            model_name='resosvp',
            name='approved_by_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Approved By Name'),
        ),
        migrations.AddField(
            model_name='resosvp',
            name='chairperson_designation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Chairperson Designation'),
        ),
        migrations.AddField(
            model_name='resosvp',
            name='chairperson_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Chairperson Name'),
        ),
        migrations.AddField(
            model_name='resosvp',
            name='end_user',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='End-user/Rep. Name'),
        ),
        migrations.AddField(
            model_name='resosvp',
            name='member1_designation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Member 1 Designation'),
        ),
        migrations.AddField(
            model_name='resosvp',
            name='member1_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Member 1 Name'),
        ),
        migrations.AddField(
            model_name='resosvp',
            name='member2_designation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Member 2 Designation'),
        ),
        migrations.AddField(
            model_name='resosvp',
            name='member2_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Member 2 Name'),
        ),
        migrations.AddField(
            model_name='resosvp',
            name='member3_designation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Member 3 Designation'),
        ),
        migrations.AddField(
            model_name='resosvp',
            name='member3_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Member 3 Name'),
        ),
        migrations.AddField(
            model_name='resosvp',
            name='member4_designation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Member 4 Designation'),
        ),
        migrations.AddField(
            model_name='resosvp',
            name='member4_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Member 4 Name'),
        ),
        migrations.AddField(
            model_name='resosvp',
            name='vice_designation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Vice Chairperson Designation'),
        ),
        migrations.AddField(
            model_name='resosvp',
            name='vice_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Vice Chairperson Name'),
        ),
    ]
